server:
  port: 8080

spring:
  application:
    name: gateway
#  cloud:
#    gateway:
#      routes:
#        - id: ticket
#          uri: http://localhost:8083
#          predicates:
#            - Path=/api/ticket/**
#          filters:
#            - RewritePath=/api/ticket/(?<segment>.*),/$\{segment}